# No hate for hiding my local IP Addresses pls
title: Home Services
services:
  Media:
    - title: Jellyseer
      description: Search for Movies, Anime and TV Shows to download.
      link: http://REDACTED:5055/
      icon:
        url: https://raw.githubusercontent.com/Fallenbagel/jellyseerr/main/public/android-chrome-512x512.png
        wrap: true
    - title: Jellyfin
      description: Website to watch Movies, Anime and TV Shows.
      link: http://REDACTED:8096/web/index.html#/home.html
      icon:
        name: openmoji:jellyfin
        wrap: true
    - title: Transmission
      description: Show length of Downloads for Movies, Anime and TV Shows.
      link: http://REDACTED:9091
      icon:
        url: https://transmissionbt.com/assets/images/Transmission_icon.png
        wrap: true
  Server:
    - title: Proxmox
      description: Managing all the VM's and LXC's.
      link: https://REDACTED:8006/#v1:0:=node%2Fpve:4
      icon:
        url: https://camo.githubusercontent.com/4e9e0bf3fcd09d6557b4eaa8f790ec17599ed6e8eb37a7e78adaa30650c8a6e3/68747470733a2f2f7777772e70726f786d6f782e636f6d2f696d616765732f70726f786d6f782f50726f786d6f785f73796d626f6c5f7374616e646172645f6865782e706e67
        wrap: true
    - title: Vault
      description: Managing the Shared Drive for Jellyfin, etc.
      link: https://REDACTED:9090/navigator
      icon:
        name: logos:ubuntu
        wrap: true
    - title: Portainer
      description: Managing most of the Containers including the arr' 
      link: https://REDACTED:9443
      icon:
        name: devicon:portainer
        wrap: true
  ARRRRR:
    - title: Sonarr
      description: Getting TV Shows and Anime
      link: http://REDACTED:8989/
      icon:
        url: https://avatars.githubusercontent.com/u/1082903?s=280&v=4
        wrap: true
    - title: Radarr
      description: Getting Movies and Anime
      link: http://REDACTED:7878/
      icon:
        url: https://static-00.iconduck.com/assets.00/radarr-icon-1845x2048-97le6lim.png
        wrap: true
    - title: Bazarr
      description: Generating Subtitles for Media automatically
      link: http://REDACTED:6767
      icon:
        url: https://user-images.githubusercontent.com/26902309/41456760-be00043e-7081-11e8-9646-1b724037b4ff.png
        wrap: true
