title: Home Services

services:
  Media:
    - title: Jellyseer
      description: Search for Movies, Anime and TV Shows.
      link: http://192.168.0.75:5055/
      icon:
        url: https://raw.githubusercontent.com/Fallenbagel/jellyseerr/main/public/android-chrome-512x512.png
        wrap: true
    - title: Jellyfin
      description: Watch Movies, Anime and TV Shows.
      link: http://192.168.0.77:8096/web/index.html#/home.html
      icon:
        name: openmoji:jellyfin
        wrap: true
    - title: Tachiyomi
      description: Read Manga, Comics and Books
      link: http://192.168.0.75:4568
      icon:
        url: https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Tachiyomi_logo.svg/800px-Tachiyomi_logo.svg.png
        wrap: true
    - title: Transmission
      description: Downloads for Movies, Anime and TV Shows.
      link: http://192.168.0.75:9091
      icon:
        url: https://transmissionbt.com/assets/images/Transmission_icon.png
        wrap: true
  Server:
    - title: Proxmox
      description: VM's and LXC's.
      link: https://192.168.0.71:8006/#v1:0:=node%2Fpve:4
      icon:
        url: https://camo.githubusercontent.com/4e9e0bf3fcd09d6557b4eaa8f790ec17599ed6e8eb37a7e78adaa30650c8a6e3/68747470733a2f2f7777772e70726f786d6f782e636f6d2f696d616765732f70726f786d6f782f50726f786d6f785f73796d626f6c5f7374616e646172645f6865782e706e67
        wrap: true
    - title: Vault
      description: Shared Drive for Jellyfin, etc.
      link: https://192.168.0.74:9090/navigator
      icon:
        name: logos:ubuntu
        wrap: true
    - title: Portainer
      description: Containers including arr' 
      link: https://192.168.0.75:9443
      icon:
        name: devicon:portainer
        wrap: true
    - title: Wireguard
      description: VPN Configuration
      link: http://192.168.0.113:10086
      icon:
        url: https://is1-ssl.mzstatic.com/image/thumb/Purple116/v4/ff/ac/78/ffac78a3-0634-81fa-fd12-b105f7af1915/AppIcon-85-220-0-4-2x.png/1200x630bb.png
        wrap: true
  Portainer:
    - title: Sonarr
      description: Torrenting TV Shows and Anime
      link: http://192.168.0.75:8989/
      icon:
        url: https://avatars.githubusercontent.com/u/1082903?s=280&v=4
        wrap: true
    - title: Radarr
      description: Torrenting Movies and Anime
      link: http://192.168.0.75:7878/
      icon:
        url: https://www.myqnap.org/wp-content/uploads/256.png
        wrap: true
    - title: Prowlarr
      description: Indexers to Torrent from 
      link: http://192.168.0.75:9696/
      icon:
        url: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/prowlarr-banner.png
        wrap: true
    - title: Bazarr
      description: Generating Subtitles for Media
      link: http://192.168.0.75:6767
      icon:
        url: https://user-images.githubusercontent.com/26902309/41456760-be00043e-7081-11e8-9646-1b724037b4ff.png
        wrap: true
  Games:
    - title: Sunshine
      description: Remote Software to play Games
      link: https://192.168.0.137:47990
      icon:
        url: https://raw.githubusercontent.com/LizardByte/Sunshine/refs/heads/master/sunshine.png
        wrap: true
    - title: Crafty
      description: Minecraft Servers
      link: https://192.168.0.117:8443
      icon:
        url: https://docs.craftycontrol.com/img/favicon.ico
        wrap: true
