services:
  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=GMT
    volumes:
      - /docker/jellyseerr:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped
